reddit/config/routes.rb
Rails.application.routes.draw do
  resources :subs do
    resources :posts
  end
  resources :users, only: [:new, :create]
  
  resource :session
end

reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  
  belongs_to :user
  belongs_to :sub
end

reddit/app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post_id, :sub_id
  
  belongs_to :post
  belongs_to :sub
end

reddit/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :moderator_id, presence: true
  
  belongs_to :moderator, 
    foreign_key: :moderator_id,    
    class_name: :User
  
  has_many :posts
end

reddit/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  attr_reader :password
  
  has_many :post_subs, inverse: :post
  has_many :subs, 
    through: :post_subs,
    source: sub
  
  after_initialize :ensure_session_token
  
  def User.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def reset_session_token
    self.session_token = generate_session_token
    self.save
    self.session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :logged_in?, :current_user
  
  def login(user)
    session[:session_token] = user.reset_session_token
  end
  
  def logout
    user.reset_session_token
    session[:session_token] = nil
  end
  
  def logged_in?
    !!current_user
  end
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_author, only: [:update, :edit]
  before_action :require_login, except: [:show]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.sub_id = params[:sub_id]
    
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:sub_id])
  end
  
  def update
    @post = Post.find(params[:sub_id])
    
    if @post.update(post_params)
      redirect_to posts_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end
  
  def show
    @post = Post.find(:params[:id])
  end
  
  def ensure_author
    redirect_to subs_url unless current_user.id == Post.find(params[:id]).user_id
  end
  
  def post_params
    params.require(:post).permit(:title, :description)
  end
end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    username = user_params[:username]
    password = user_params[:password]
    @user = User.find_by_credentials(username, password)
    
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid Username/Password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :ensure_moderator, only: [:update, :edit]
  before_action :require_login, except: [:show, :index]
  
  def new
    @sub = Sub.new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def edit
    @sub = Sub.find(params[:id])
  end
  
  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      fail
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def show
    @sub = Sub.find(params[:id])
  end
  
  def index
    @subs = Sub.all
  end
  
  def ensure_moderator
    redirect_to subs_url unless current_user.id == Sub.find(params[:id]).moderator_id
  end
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save!
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="sub" value="Log Out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign In</a>
      <a href="<%= new_user_url %>">Sign up</a>
    <% end %>
    
    <br>
    
    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li>error</li>
          <br>
        <% end %>
      </ul>
    <% end %>
    
    <%= yield %>
  </body>
</html>

reddit/app/views/posts/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <br>
  <label>
    Title
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>
  <label>
    URL
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <br>
  <label>
    Content
    <textarea name="post[content]" rows="8" cols="80"><%= post.content %></textarea>
  </label>
  <br>
  
  <input type="submit" value="<%= button %>">
</form>

reddit/app/views/posts/new.html.erb
<h1>Make a new post</h1>

<%= render "form", 
    action: sub_posts_url,
    method: "post",
    post: @post,
    button: "Create Post"
  %>

reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render "form", 
    action: sub_url(@sub),
    method: "patch",
    subber: @sub,
    button: "Edit Sub"
  %>

reddit/app/views/subs/index.html.erb
<h1>All subs</h1>

<ul>
  <% @subs.each do |subber| %>
    <li><a href="<%= sub_url(subber) %>"><%= subber.title %></a></li>
  <% end %>
</ul>

<a href="<%= new_sub_url %>">Add New Sub</a>

reddit/app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render "form", 
    action: subs_url,
    method: "post",
    subber: @sub,
    button: "Add New Sub"
  %>

reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h3><%= @sub.description %></h3>
by <%= User.find(@sub.moderator_id).username %>

<br>
<a href="<%= edit_sub_url %>">Edit Sub</a>
<br>
<a href="<%= new_sub_post_url(@sub) %>">New Post</a>
<br>
<ul>
  <% @sub.posts.each do |post| %>
    <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
  <% end %>
</ul>

reddit/app/views/users/new.html.erb
<h1>Users#new</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>
    Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  
  <label>
    Password
    <input type="text" name="user[password]" value="<%= @user.password %>">
  </label>
  
  
  <input type="submit" value="Create New User">
</form>